#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <memory>

#include <QButtonGroup>
#include <QMainWindow>

class View;

class DataBinding;

namespace Ui {
    class MainWindow;
}

/**
 * @class MainWindow
 *
 * The main graphical user interface class (GUI class) for our application.
 */
class MainWindow : public QMainWindow {
    Q_OBJECT
public:
    MainWindow(QWidget *parent = 0);
    ~MainWindow();

private:
    // Auto-generated by Qt. DO NOT RENAME!
    Ui::MainWindow *ui;

    // Enables or disables the UI controls.
    void setAllEnabled(bool enabled);

    // Sets up the data bindings between the UI and app settings
    void dataBind();

    QList<DataBinding*> m_bindings;
    QList<QButtonGroup*> m_buttonGroups;

public slots:
    // Used internally to keep data bindings and the user interface in sync.
    void settingsChanged();
};

#endif // MAINWINDOW_H
